apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicwebapp-deployment
spec:
  selector:
    matchLabels:
      app: basicwebapp
  replicas: 2
  template:
    metadata:
      labels:
        app: basicwebapp
    spec:
      containers:
        - name: basicwebapp
          image: basicwebapp:v1
          ports:
            - containerPort: 3000
          imagePullPolicy: Never