apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-deployment
spec:
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
        - name: psql
          image: psql:v1
          ports:
            - containerPort: 5432
          imagePullPolicy: Never